### PR TITLE
Remove virtio model reference on sriov

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

The kubevirt validation allows passing through models on sriov devices
which it should not, and they have no effect. Removing them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by rmohr** [comment]
@dominikholler as you suspected, the model is ignored.

**Comment by dominikholler** [comment]
@rmohr thanks for follow up. The change looks good to me. `networkInterfaceMultiqueue` might be still ignored, but if we keep it, it might be a good hint for users who wants to test with virtio virtual NICs.
@EdDev  are you fine with this code change?

**Comment by EdDev** [comment]
> EdDev are you fine with this code change?

Looks right to me.
We should probably add warning events in the validation, but unfortunately we cannot block it there (due to backward compatibility).
Is it worth adding an event with a warning @ kubevirt/kubevirt?

**Review by EdDev — APPROVED** [review]

**Pull request merged**
