### PR TITLE
fix: disable SMM on Fedora for s390x architecture

### PR DESCRIPTION
**Pull request by nestoracunablanco**
**What this PR does / why we need it**: s390x enablement

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Comment by 0xFelix** [comment]
Ah yes, this should have been tested before, but we have two bots in this repo...

**Comment by nestoracunablanco** [comment]
@0xFelix: Could we manually trigger the tests in the master branch to ensure that everything is functioning correctly?

**Comment by 0xFelix** [comment]
This change is very minimal, so I don't expect it to cause any issues.

If CI passes in your next PR (https://github.com/kubevirt/common-templates/pull/633), it should be fine.

**Pull request merged**
