### PR TITLE
Expand I/O threads support for high performance templates

### PR DESCRIPTION
**Pull request by nelsonspbr**
**What this PR does / why we need it**: 

This PR expands I/O threads support for high performance templates. Specifically, these changes enforce the use of dedicated CPU placement (pinning) when I/O threads are enabled. Also, it dedicates an I/O thread for the root (main) disk.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nelsonspbr** [comment]
@omeryahud @ksimon1 I am getting weird errors in the `e2e-azure-nested-common-templates-unit-tests` ([here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_common-templates/315/pull-ci-kubevirt-common-templates-master-e2e-azure-nested-common-templates-unit-tests/1354794452803129344)).

```
level=error msg="Error: Request \"Create IAM Members roles/compute.viewer
serviceAccount:ci-op-4t4s6stc-1bfbc-gpp7g-w@openshift-gce-devel-ci.iam.gserviceaccount.com
for \\\"project \\\\\\\"openshift-gce-devel-ci\\\\\\\"\\\"\" returned error:
Batch request and retried single request \"Create IAM Members
roles/compute.viewer
serviceAccount:ci-op-4t4s6stc-1bfbc-gpp7g-w@openshift-gce-devel-ci.iam.gserviceaccount.com
for \\\"project \\\\\\\"openshift-gce-devel-ci\\\\\\\"\\\"\" both failed. Final
error: Error applying IAM policy for project \"openshift-gce-devel-ci\": Error
setting IAM policy for project \"openshift-gce-devel-ci\": googleapi: Error 400:
The number of members in the policy (1,501) is larger than the maximum allowed
size 1,500., badRequest"
```

Any thoughts on what this could be?

**Comment by ksimon1** [comment]
These are error in infrastructure, can you please check the openshift ci slack channel?

**Comment by nelsonspbr** [comment]
Done, the issue was solved and the tests passed.

**Comment by ksimon1** [comment]
@omeryahud @akrejcir @vatsalparekh @shwetaap @kwiesmueller  can you please check this PR?

**Comment by akrejcir** [comment]
I have 2 questions:
- Why are IO threads only used in RHEL and Fedora templates?
- Why is additional IO thread dedicated for the root disk? Does it provide a performance benefit?

**Comment by nelsonspbr** [comment]
@akrejcir 

> * Why are IO threads only used in RHEL and Fedora templates?

There is parallel work to extend high performance tunables to other templates, such as Windows (e.g., https://github.com/kubevirt/common-templates/pull/317). Not sure about CentOS and others, though.

> * Why is additional IO thread dedicated for the root disk? Does it provide a performance benefit?

It should be a slight improvement compared to just using the `shared` policy, which dedicates a shared IO thread for all disks (including the root disk). It depends on other aspects, such as if the other disks sharing the IO thread also observe intensive utilization.

**Comment by akrejcir** [comment]
> > * Why are IO threads only used in RHEL and Fedora templates?
> 
> There is parallel work to extend high performance tunables to other templates, such as Windows (e.g., #317). Not sure about CentOS and others, though.

Ok.

> > * Why is additional IO thread dedicated for the root disk? Does it provide a performance benefit?
> 
> It should be a slight improvement compared to just using the `shared` policy, which dedicates a shared IO thread for all disks (including the root disk). It depends on other aspects, such as if the other disks sharing the IO thread also observe intensive utilization.

I'm asking because I assumed that there is a noticable performance improvement of using 1 IO thread instead of 0, but using more than 1 IO thread is only useful for certain heavy IO applications like a database. I did not see any measurements, I have only read it on a mailing list some time ago.

**Review by omeryahud — APPROVED** [review]
/lgtm

**Pull request merged**
