### PR TITLE
fix hard coded fedora name in annotations

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
fix hard coded fedora name in annotations
**Which issue(s) this PR fixes** :
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1917210

**Release note**:
``` 
fixed hard coded fedora name in annotations
```
Signed-off-by: Karel Simon <ksimon@redhat.com>

### CODE REVIEW

**Comment by omeryahud** [comment]
@ksimon1 I think this would show `fedora32+ VM`, can you make it `Fedora X+ VM`, just to make it more readable?

**Comment by ksimon1** [comment]
> @ksimon1 I think this would show `fedora32+ VM`, can you make it `Fedora X+ VM`, just to make it more readable?

No, this patch will generate correct names:
```
    openshift.io/display-name: "Fedora 32+ VM"
    description: >-
      Template for Fedora 32 VM or newer.
```

**Comment by omeryahud** [comment]
> > @ksimon1 I think this would show `fedora32+ VM`, can you make it `Fedora X+ VM`, just to make it more readable?
> 
> No, this patch will generate correct names:
> 
> ```
>     openshift.io/display-name: "Fedora 32+ VM"
>     description: >-
>       Template for Fedora 32 VM or newer.
> ```

Great! Thanks!

**Pull request merged**
