### PR TITLE
Print templates to stdout in CI

### PR DESCRIPTION
**Pull request by omeryahud**
**What this PR does / why we need it**:
Printing templates to stdout during testing so reviewers don't have to pull the patch and generate the templates themselves

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by omeryahud** [comment]
@ksimon1 Karel, looks like all tests are failing due to timeouts, can you take a look?

**Comment by ksimon1** [comment]
/lgtm
can you please rebase this PR on latest master?

**Pull request merged**
