### PR TITLE
Centos stream

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
add centos stream 8 and 9 templates 
update osinfo

delete centos 8 template because centos 8 is EOL

**Release note**:
```
Drop centos 8 template because centos 8 is EOL
Add centos stream 8 and 9
```

### CODE REVIEW

**Comment by ksimon1** [comment]
this PR https://github.com/openshift/release/pull/24986 has to be merged as well

**Review by dominikholler — APPROVED** [review]
@rnetser @yaacov Please note that this change changes more than just the "openshift.io/display-name" , this is a clean update which changes also the annotation "name.os.template.kubevirt.io/centos8" to "name.os.template.kubevirt.io/centos-stream8", has the label "os.template.kubevirt.io/centos-stream8" instead of "os.template.kubevirt.io/centos8", and uses "stream" inside "vm.kubevirt.io/template" and "vm.kubevirt.io/os". Please let us know if this creates any trouble.

/lgtm

**Pull request merged**
