### PR TITLE
increased kubevirt version to v0.18.0

### PR DESCRIPTION
**Pull request by ksimon1**

### CODE REVIEW

**Comment by fromanirh** [comment]
Don't we need to fetch the last changes from the `ci` submodule? besides this, LGTM

**Comment by ksimon1** [comment]
no we don't need it.

**Comment by ksimon1** [comment]
@MarSik ping, can you review this?

**Comment by ksimon1** [comment]
Closing in favour of better approach introduced here: https://github.com/kubevirt/common-templates/blob/master/automation/test.sh#L41

**Pull request closed without merging**
