### PR TITLE
Add emulator thread

### PR DESCRIPTION
**Pull request by nelsonspbr**
**What this PR does / why we need it**: This PR adds emulator thread pinning to high performance templates.

**Special notes for your reviewer**:
- added `emulatorthread` item to `generate-templates.yaml` and corresponding logic to `.tpl.yaml` files control template generation;
- emulator thread pinning requires dedicated CPU placement; current logic adds both options using the same item;
- platforms that do not specify a high performance template did not have their `.tpl.yaml` files modified;
- as an "extra" modification, this PR also reformats `generate-templates.yaml` to align item configuration;

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nelsonspbr** [comment]
- retrieved debug information using instrumentation added to separate PR (see https://github.com/kubevirt/common-templates/pull/297)
- output: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_common-templates/297/pull-ci-kubevirt-common-templates-master-e2e-azure-nested-common-templates-fedora/1346477805512167424#1:build-log.txt%3A3055

```
Name:           virt-launcher-fedora-highperformance-tiny-cxdbv
Namespace:      kubevirt
Priority:       0
Node:           <none>
Labels:         kubevirt.io=virt-launcher
                kubevirt.io/created-by=136f17ee-2da6-414f-9670-622baec69a39
                kubevirt.io/domain=fedora-highperformance-tiny
                kubevirt.io/size=tiny
Annotations:    kubevirt.io/domain: fedora-highperformance-tiny
                openshift.io/scc: kubevirt-controller
                traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
Status:         Pending
...
Node-Selectors:  cpumanager=true
                 kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From  Message
  ----     ------            ----       ----  -------
  Warning  FailedScheduling  <unknown>        0/6 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s) didn't match node selector.
  Warning  FailedScheduling  <unknown>        0/6 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s) didn't match node selector.
```

- unable to schedule due to a number of reasons
    - devices.kubevirt.io/kvm
    - devices.kubevirt.io/tun
    - devices.kubevirt.io/vhost-net
    - didn't match node selector

- I had issues before running manual tests using the high performance profiles because of the `cpumanager=true` label requirement, which could be causing the last error
- added node debug information to #297 and re-running tests

**Comment by nelsonspbr** [comment]
- new set of tests executed
- Fedora case: node debug information at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_common-templates/297/pull-ci-kubevirt-common-templates-master-e2e-azure-nested-common-templates-fedora/1346554012249362432#1:build-log.txt%3A4714
- indeed none of the available nodes for the test have the `cpumanager=true` label, causing the pods to not be scheduled and therefore failing the test after timeout

```
NAME                                                 STATUS   ROLES    AGE   VERSION           LABELS
ci-op-r9mfdx81-e7bc6-4hbtn-master-0                  Ready    master   43m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D8s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-2,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-master-0,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.kubernetes.io/instance-type=Standard_D8s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-2
ci-op-r9mfdx81-e7bc6-4hbtn-master-1                  Ready    master   43m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D8s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-1,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-master-1,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.kubernetes.io/instance-type=Standard_D8s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-1
ci-op-r9mfdx81-e7bc6-4hbtn-master-2                  Ready    master   42m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D8s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-3,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-master-2,kubernetes.io/os=linux,node-role.kubernetes.io/master=,node.kubernetes.io/instance-type=Standard_D8s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-3
ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus1-gfw9q   Ready    worker   33m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-1,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus1-gfw9q,kubernetes.io/os=linux,kubevirt.io/schedulable=true,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=Standard_D4s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-1
ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus2-7nl2w   Ready    worker   34m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-2,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus2-7nl2w,kubernetes.io/os=linux,kubevirt.io/schedulable=true,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=Standard_D4s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-2
ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus3-mdpfk   Ready    worker   34m   v1.19.0+9c69bdc   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/instance-type=Standard_D4s_v3,beta.kubernetes.io/os=linux,failure-domain.beta.kubernetes.io/region=centralus,failure-domain.beta.kubernetes.io/zone=centralus-3,kubernetes.io/arch=amd64,kubernetes.io/hostname=ci-op-r9mfdx81-e7bc6-4hbtn-worker-centralus3-mdpfk,kubernetes.io/os=linux,kubevirt.io/schedulable=true,node-role.kubernetes.io/worker=,node.kubernetes.io/instance-type=Standard_D4s_v3,node.openshift.io/os_id=rhcos,topology.kubernetes.io/region=centralus,topology.kubernetes.io/zone=centralus-3
```

- for now, suggestion is to properly label worker nodes used in the test
- will attempt to do so using the debug branch #297

**Comment by nelsonspbr** [comment]
- using debug branch #297, pushed modifications to `automation/test-linux.sh` to add the `cpumanager=true` label to worker nodes, which should fix issues with the execution of tests with high performance profiles

**Comment by nelsonspbr** [comment]
Tests `e2e-azure-nested-common-templates-rhel7` and `e2e-azure-nested-common-templates-rhel8` fail with `Insufficient cpu`:

```
Events:
  Type     Reason            Age        From  Message
  ----     ------            ----       ----  -------
  Warning  FailedScheduling  <unknown>        0/6 nodes are available: 1 node(s) had volume node affinity conflict, 2 Insufficient cpu, 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net.
  Warning  FailedScheduling  <unknown>        0/6 nodes are available: 1 node(s) had volume node affinity conflict, 2 Insufficient cpu, 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net.
```

Profiles are [`rhel7-highperformance-large`](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_common-templates/297/pull-ci-kubevirt-common-templates-master-e2e-azure-nested-common-templates-rhel7/1347027701675855872#1:build-log.txt%3A7247) and [`rhel8-highperformance-large`](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_common-templates/297/pull-ci-kubevirt-common-templates-master-e2e-azure-nested-common-templates-rhel8/1347027701713604608#1:build-log.txt%3A8459), respectively. These profiles require 2 CPUs + at least one for the emulator thread.

**Comment by omeryahud** [comment]
@nelsonspbr Hi Nelson! Have you investigated the option of modifying the CI cluster configuration? Maybe setting a different profile in the job configuration file: https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml#L150
(I am guessing this is related, haven't checked what the available profiles are)

**Comment by nelsonspbr** [comment]
@omeryahud Sounds good Omer. Is there an obvious way to test this kubevirt/common-templates branch against a potential custom branch of openshift/release? Or, in broader terms, how would I test this modification? And right, I will try to figure out the available profiles.

**Comment by omeryahud** [comment]
> 
> 
> @omeryahud Sounds good Omer. Is there an obvious way to test this kubevirt/common-templates branch against a potential custom branch of openshift/release? Or, in broader terms, how would I test this modification? And right, I will try to figure out the available profiles.

I think we can do something like this:

1. Create a branch in `kubevirt/common-templates` that you freely merge to: `emulator-branch`
2. Create a new config file in `openshift/release` to generate jobs for that branch (see here how it can be done https://github.com/openshift/release/pull/14754)
3. Modify the `emulator-branch` and the new config file until everything works
4. Update the `master` branch test config file if `openshift/release` (https://github.com/openshift/release/blob/master/ci-operator/config/kubevirt/common-templates/kubevirt-common-templates-master.yaml) to include the working configuration
5. Open a PR to merge `emulator-branch` to `master`

**Comment by nelsonspbr** [comment]
Got it. I had a look at [kubevirt-ssp-operator-release-v0.1.yaml](https://github.com/omeryahud/release/blob/6ec97fcd7c287940eaa6979dfa336854114c3046/ci-operator/config/kubevirt/ssp-operator/kubevirt-ssp-operator-release-v0.1.yaml) — basically what "points" to the right repo/branch is this bit, right?

```yaml
zz_generated_metadata:
  branch: release-v0.1
  org: kubevirt
  repo: ssp-operator
```

I am still looking at how to increase the CPU resources. I did not find alternatives to `azure4`, but I found [this](https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh#L18), which I think it is how these resources are allocated.

```yaml
cat >> "${CONFIG}" << EOF
baseDomain: ci.azure.devcluster.openshift.com
compute:
- name: worker
  platform:
    azure:
      type: Standard_D4s_v3
platform:
  azure:
    baseDomainResourceGroupName: os4-common
    region: ${REGION}
EOF
```
That is different from what is done for [AWS](https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/aws/ipi-conf-aws-commands.sh#L32), for instance, where the compute node type is parameterized:

```yaml
cat >> "${CONFIG}" << EOF
baseDomain: origin-ci-int-aws.dev.rhcloud.com
controlPlane:
  name: master
  platform:
    aws:
      zones:
      - ${ZONE1:-${REGION}a}
      - ${ZONE2:-${REGION}b}
compute:
- name: worker
  platform:
    aws:
      type: ${COMPUTE_NODE_TYPE}
      zones:
      - ${ZONE1:-${REGION}a}
      - ${ZONE2:-${REGION}b}
platform:
  aws:
    region: ${REGION}
    userTags:
      expirationDate: ${expiration_date}
EOF
```

And [here](https://github.com/openshift/release/blob/1b47ddb81d99e0424efc588dcfd7f046866a227f/ci-operator/config/openshift/origin-aggregated-logging/openshift-origin-aggregated-logging-master.yaml#L134) an example of how the parameter is used.

I am thinking of parameterizing this field ([here](https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/azure/ipi-conf-azure-commands.sh#L18)) while providing a `Standard_D4s_v3` default right before in the same script.

**Comment by nelsonspbr** [comment]
Closing in favor of https://github.com/kubevirt/common-templates/pull/309.

**Pull request closed without merging**
