### PR TITLE
perf: optimizes check for updated machineconfigpool

### PR DESCRIPTION
**Pull request by nestoracunablanco**
This optimization is particularly beneficial when running the test scripts a second time within the same cluster.

**What this PR does / why we need it**: s390x enablement

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

**Comment by nestoracunablanco** [comment]
@0xFelix @fossedihelm @geetikakay anything else you need for a lgtm label?

**Pull request merged**
