### PR TITLE
Use the Fedora Release url - https://getfedora.org/releases.json to identify the latest releases, and their image download links.

### PR DESCRIPTION
**Pull request by shwetaap**
**What this PR does / why we need it**:
Use the Fedora Release url - https://getfedora.org/releases.json to identify the latest releases, and their image download links

**Release note**:

```release-note
None
```
Signed-off-by: Shweta Padubidri <spadubid@redhat.com>

### CODE REVIEW

**Review by sarahbx — COMMENTED** [review]
lgtm 👍 pending CI

**Comment by kwiesmueller** [comment]
/lgtm
you could download the releases.json only once, but I don't expect it to cause problems

**Pull request merged**
