### PR TITLE
add support for stimer direct to windows templates

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
add support for stimer direct to windows templates

/hold

**Release note**:
```
add support for stimer direct to windows templates
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by akrejcir** [comment]
I see this PR is on hold. What is it waiting for?

**Comment by ksimon1** [comment]
for newest v0.40 kubevirt release

**Pull request merged**
