### PR TITLE
README: Fix typos in the CentOS entries

### PR DESCRIPTION
**Pull request by fidencio**
**What this PR does / why we need it**:

This PR brings on only cosmetic fixes, such as renaming "Cent OS" to "CentOS", and also having the CentOS 8 entry pointing to the correct template (centos8 one, instead of the centos7).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by fidencio** [comment]
@omeryahud, seems the whole azure infra is busted.
Is there some common place to report such issues?

**Comment by omeryahud** [comment]
@fidencio Hi Fabiano!
We are currently working on migrating our tests to OCP ci (the azure lanes you are seeing), but they are not complete yet (we have a PR open to complete the migration), so for now, you should only care about the `pull-e2e-*` lanes

**Comment by fidencio** [comment]
> @fidencio Hi Fabiano!
> We are currently working on migrating our tests to OCP ci (the azure lanes you are seeing), but they are not complete yet (we have a PR open to complete the migration), so for now, you should only care about the `pull-e2e-*` lanes

Ack! Thanks for the explanation!

**Comment by omeryahud** [comment]
/override ci/prow/e2e-azure-nested-common-templates-centos6
/override ci/prow/e2e-azure-nested-common-templates-centos7
/override ci/prow/e2e-azure-nested-common-templates-centos8
/override ci/prow/e2e-azure-nested-common-templates-fedora
/override ci/prow/e2e-azure-nested-common-templates-opensuse
/override ci/prow/e2e-azure-nested-common-templates-rhel6
/override ci/prow/e2e-azure-nested-common-templates-rhel7
/override ci/prow/e2e-azure-nested-common-templates-rhel8
/override ci/prow/e2e-azure-nested-common-templates-ubuntu
/override ci/prow/e2e-azure-nested-common-templates-unit-tests
/override ci/prow/e2e-azure-nested-common-templates-windows10
/override ci/prow/e2e-azure-nested-common-templates-windows2012
/override ci/prow/e2e-azure-nested-common-templates-windows2016
/override ci/prow/e2e-azure-nested-common-templates-windows2019

**Pull request merged**
