### PR TITLE
Update osinfo-db to v20230308-2-g2a5ff068

### PR DESCRIPTION
**Pull request by ksimon1**
Update osinfo-db to v20230308-2-g2a5ff068
**Release note**:
```release-note
Update osinfo-db to v20230308-2-g2a5ff068
```

### CODE REVIEW

**Review by fossedihelm — APPROVED** [review]
Thanks!
Since win11 data has been released, maybe we can remove the `osinfo-db-override/os/microsoft.com` directory. WDYT? Maybe in a follow up PR?

**Comment by 0xFelix** [comment]
/approve

@fossedihelm Sounds good! Can you create the PR?

**Comment by fossedihelm** [comment]
> /approve
> 
> @fossedihelm Sounds good! Can you create the PR?

Sure! https://github.com/kubevirt/common-templates/pull/519

**Pull request merged**
