### PR TITLE
Update osinfo-db to v20230719-47-g592b3be8

### PR DESCRIPTION
**Pull request by ksimon1**
Update osinfo-db to v20230719-47-g592b3be8
**Release note**:
```release-note
Update osinfo-db to v20230719-47-g592b3be8
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Comment by ksimon1** [comment]
closing in favor of https://github.com/kubevirt/common-templates/pull/552

**Pull request closed without merging**
