### PR TITLE
Update osinfo-db to v20230719-7-g74425d30

### PR DESCRIPTION
**Pull request by ksimon1**
Update osinfo-db to v20230719-7-g74425d30
**Release note**:
```release-note
Update osinfo-db to v20230719-7-g74425d30
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Comment by jcanocan** [comment]
This PR is blocked by CI issue. IMHO we can force merge it without tests.

**Comment by lyarwood** [comment]
/lgtm

Agreed, we can /override here.

**Pull request merged**
