### PR TITLE
Remove Windows 2k12 template

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Remove Windows 2k12 template.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Jira: https://issues.redhat.com/browse/CNV-41784

**Special notes for your reviewer**:

**Release note**:

```release-note
Removed Windows 2k12 from the available templates
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by ksimon1** [comment]
@fossedihelm to which OCP V version this has to go?

**Comment by fossedihelm** [comment]
@ksimon1 starting from 4.16

**Comment by fossedihelm** [comment]
@ksimon1 do you want me to do the backport?

**Pull request merged**
