### PR TITLE
Fix os/flavor/workload annotations location

### PR DESCRIPTION
**Pull request by sradco**
Signed-off-by: Shirly Radco <sradco@redhat.com>

**What this PR does / why we need it**:

Moved vm.kubevirt.io/os, vm.kubevirt.io/workload,
vm.kubevirt.io/flavor annotations under
spec.template.metadata so that they will be copied
to the VMI object.

They are used as labels for the kubevirt_vmi_phase_count metric.
Annotations from the new location are copied to the VMI.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by sradco** [comment]
@ shwetaap @rnetser Hi, Can you please review my patch?

**Comment by omeryahud** [comment]
@sradco Hi Shirley, aren't VM annotations/labels automatically passed to VMIs?

**Comment by sradco** [comment]
@omeryahud The annotations are only copied when they are under the spec.template.metadata, See here:
https://github.com/kubevirt/kubevirt/blob/8363e066296c338943b4029a25aa524ca3fa124d/pkg/virt-controller/watch/vm.go#L796
https://github.com/kubevirt/kubevirt/blob/8363e066296c338943b4029a25aa524ca3fa124d/pkg/virt-controller/watch/vm_test.go#L1052

**Comment by omeryahud** [comment]
> @omeryahud The annotations are only copied when they are under the spec.template.metadata, See here:
> https://github.com/kubevirt/kubevirt/blob/8363e066296c338943b4029a25aa524ca3fa124d/pkg/virt-controller/watch/vm.go#L796
> https://github.com/kubevirt/kubevirt/blob/8363e066296c338943b4029a25aa524ca3fa124d/pkg/virt-controller/watch/vm_test.go#L1052

Ah I see, thanks.
/lgtm
/approve

**Pull request merged**
