### PR TITLE
feat: enable virtctl download based on host architecture

### PR DESCRIPTION
**Pull request by nestoracunablanco**
**What this PR does / why we need it**: s390x enablement

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note NONE

```

### CODE REVIEW

**Comment by nestoracunablanco** [comment]
Hi @0xFelix, it appears that the first test is experiencing a timeout issue. If you give me the "ok-to-test", I can run the tests one by one and keep you updated when everything is green.

**Comment by 0xFelix** [comment]
@nestoracunablanco Looks like the CI resources are exhausted, we need to wait.

**Comment by ksimon1** [comment]
we are experiencing issues with CDI in e2e tests. 
This PR is not causing the issues anf thus I am merging it.

**Pull request merged**
