### PR TITLE
feat: s390x centos-stream9 enablement

### PR DESCRIPTION
**Pull request by nestoracunablanco**
**What this PR does / why we need it**: s390x enablement

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ksimon1** [comment]
/approve
@fossedihelm can you please review this PR?

**Comment by fossedihelm** [comment]
/lgtm
just a note: containerdisk for s390x is not available

**Comment by fossedihelm** [comment]
> Thanks @fossedihelm @ksimon1! FYI: centos-stream 9 containerdisk is available for s390x. Link [here](https://quay.io/repository/containerdisks/centos-stream?tab=tags).

In `osinfo-db/data/os/centos.org/centos-stream-9.xml` I only see x86_64
```xml
    <image arch="x86_64" format="containerdisk" cloud-init="true">
      <url>docker://quay.io/containerdisks/centos-stream:9</url>
    </image>
    <image arch="aarch64" format="qcow2" cloud-init="true">
      <url>https://cloud.centos.org/centos/9-stream/aarch64/images/CentOS-Stream-GenericCloud-9-latest.aarch64.qcow2</url>
    </image>
    <image arch="ppc64le" format="qcow2" cloud-init="true">
      <url>https://cloud.centos.org/centos/9-stream/ppc64le/images/CentOS-Stream-GenericCloud-9-latest.ppc64le.qcow2</url>
    </image>
    <image arch="s390x" format="qcow2" cloud-init="true">
      <url>https://cloud.centos.org/centos/9-stream/s390x/images/CentOS-Stream-GenericCloud-9-latest.s390x.qcow2</url>
    </image>
    <image arch="x86_64" format="qcow2" cloud-init="true">
      <url>https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-latest.x86_64.qcow2</url>
    </image>
```

**Comment by 0xFelix** [comment]
@fossedihelm Good catch, we totally missed that. This needs to be updated for a bunch of distributions (Fedora, CentOS, Ubuntu, ...).

**Pull request merged**
