### PR TITLE
Add fossedihelm to reviewer list

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Add fossedihelm to reviewer list

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```
/cc @0xFelix

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by akrejcir** [comment]
No need to run CI.

/override ci/prow/e2e-gcp-common-templates-centos-stream8
/override ci/prow/e2e-gcp-common-templates-centos-stream8
/override ci/prow/e2e-gcp-common-templates-centos6
/override ci/prow/e2e-gcp-common-templates-centos7 
/override ci/prow/e2e-gcp-common-templates-fedora
/override ci/prow/e2e-gcp-common-templates-opensuse
/override ci/prow/e2e-gcp-common-templates-rhel7 
/override ci/prow/e2e-gcp-common-templates-rhel8
/override ci/prow/e2e-gcp-common-templates-rhel9
/override ci/prow/e2e-gcp-common-templates-ubuntu
/override ci/prow/e2e-gcp-common-templates-unit-tests 
/override ci/prow/e2e-gcp-common-templates-windows10
/override ci/prow/e2e-gcp-common-templates-windows11
/override ci/prow/e2e-gcp-common-templates-windows2012
/override ci/prow/e2e-gcp-common-templates-windows2016
/override ci/prow/e2e-gcp-common-templates-windows2019
/override ci/prow/e2e-gcp-common-templates-windows2022
/override ci/prow/e2e-gcp-go-tests

**Pull request merged**
