### PR TITLE
update owners file to reflect current contributors

### PR DESCRIPTION
**Pull request by dominikholler**
Signed-off-by: Dominik Holler <dholler@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ksimon1** [comment]
Geetika has to add her into kubevirt org with the same PR as this one https://github.com/kubevirt/project-infra/pull/2043

**Comment by dominikholler** [comment]
@geetikakay can you please join the kubevirt project like described in https://github.com/kubevirt/community/blob/46b92f1c3ce5488aa55ff13d7013672339eaf646/membership_policy.md#established-community-members ?

**Comment by geetikakay** [comment]
> @geetikakay can you please join the kubevirt project like described in https://github.com/kubevirt/community/blob/46b92f1c3ce5488aa55ff13d7013672339eaf646/membership_policy.md#established-community-members ?

Done . I refer the checklist mentioned in https://github.com/kubevirt/project-infra/pull/2043.

**Comment by ksimon1** [comment]
@geetikakay can you please create the same PR as Ondrej did in https://github.com/kubevirt/project-infra/pull/2043?

**Pull request merged**
