### PR TITLE
Rename parameters to DATA_SOURCE_NAME and DATA_SOURCE_NAMESPACE

### PR DESCRIPTION
**Pull request by akrejcir**
**What this PR does / why we need it**:
Rename from SRC_PVC_NAME to DATA_SOURCE_NAME,
and from SRC_PVC_NAMESPACE to DATA_SOURCE_NAMESPACE.

**Release note**:
```release-note
Renamed parameters in templates.
```

### CODE REVIEW

**Comment by ksimon1** [comment]
@akrejcir UI is ready for this change?

**Comment by akrejcir** [comment]
They are working on it right now.

**Comment by akrejcir** [comment]
Waiting for UI
/hold

**Comment by dominikholler** [comment]
@akrejcir Can you please share the motivation for this change in the commit message?

**Comment by dominikholler** [comment]
@akrejcir Can you please share the motivation for this change in the commit message?
@yaacov Is UI ready to get this update?

**Comment by yaacov** [comment]
> @yaacov Is UI ready to get this update?

No, unfortunately the current UI assume the PVC source is in a parameter called  `SRC_PVC_NAME/NAMESPCE`

p.s. Once we move to using parameters "as is" this will no longer be a problem, but in 4.10 the parameter name is hardcoded in the UI.

**Comment by dominikholler** [comment]
> No, unfortunately the current UI assume the PVC source is in a parameter called SRC_PVC_NAME/NAMESPCE
> p.s. Once we move to using parameters "as is" this will no longer be a problem, but in 4.10 the parameter name is hardcoded in the UI.

@yaacov Do you plan to modify the name of the parameter in 4.10 ?

**Comment by yaacov** [comment]
> @yaacov Do you plan to modify the name of the parameter in 4.10 ?

We didn't know about the name change, so we didn't make any plans

Note I:
if we do support it, we will have to support both conventions, and check for both names because we need to be backword compatible,  
Note II:
It will be nice if we wait with the name change to 4.11, where we plan to remove the practice of giving meaning to template parameters in the UI (CNV-14778)

cc:// @tnisan

**Comment by ksimon1** [comment]
/cherrypick release-v0.19
Backporting forgotten PR

**Pull request merged**
