### PR TITLE
test win2019

### PR DESCRIPTION
**Pull request by ksimon1**
Do NOT merge.
This is test PR to run win 2019 test
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by fabiand** [comment]
It seems as if the win2k12r2 template is used in the failing windows2019 test:
`cluster-up/kubectl.sh get vmi win2k12r2-server-medium -o json`

But shouldn't this use a windows2019 tempalte?
Also: I think the hyperv flags are used in the template. Can you try to drpo the flags for now?

**Comment by ksimon1** [comment]
We use win2k12r2 template for all supported windows. Lets test it without hyperv flags.

**Comment by fabiand** [comment]
How are we doing on this testing?

**Comment by ksimon1** [comment]
@fabiand 
The win2019 is booting, but i had to remove whole clock section from template
So i am trying to identify which attribute is failing. And it means one test run for each attribute

**Comment by ksimon1** [comment]
Closing in favour of: https://github.com/kubevirt/common-templates/pull/126

**Pull request closed without merging**
