### PR TITLE
Download oc binary from new location and readd intltool

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Download the latest stable oc binary in `builder/Dockerfile` from the new
location on the mirror.

intltool was removed by accident from the dependencies. Readd it.

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by akrejcir** [comment]
This PR fixes the failing CI.

/override ci/prow/e2e-azure-common-templates-unit-tests

**Comment by ksimon1** [comment]
Merging to unlock failing ci

**Pull request merged**
