### PR TITLE
fix wrong api version in rhel 9 template

### PR DESCRIPTION
**Pull request by ksimon1**
**What this PR does / why we need it**:
fix wrong api version in rhel 9 template

**Special notes for your reviewer**:

**Release note**:
```
NONE
```
Signed-off-by: Karel Šimon <ksimon@redhat.com>

### CODE REVIEW

**Comment by dominikholler** [comment]
Thanks, looks good.

**Comment by dominikholler** [comment]
Looks even better.

**Comment by ksimon1** [comment]
@omeryahud Can you please review?
/retest

**Pull request merged**
