### PR TITLE
Add windows2022 template

### PR DESCRIPTION
**Pull request by Barakmor1**
Add Windows server 2022 template

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Add Windows server 2022 template
```

### CODE REVIEW

**Comment by Barakmor1** [comment]
@ksimon1 
Waiting for https://github.com/openshift/release/pull/31683 to land.
/hold

**Comment by acardace** [comment]
/unhold

https://github.com/openshift/release/pull/31683 has been merged.

**Comment by Barakmor1** [comment]
@iholder-redhat 
@ksimon1 
I think we need to create backport PRs for
https://github.com/kubevirt/kubevirt/pull/8359#event-7360550567

**Comment by iholder-redhat** [comment]
> @iholder-redhat @ksimon1 I think we need to create backport PRs for [kubevirt/kubevirt#8359 (comment)](https://github.com/kubevirt/kubevirt/pull/8359#event-7360550567) In the tests we are using v0.56 and also we should consider other versions with the update of qemu.

There you go: https://github.com/kubevirt/kubevirt/pull/8450.
For v0.53 I [didn't have such luck](https://github.com/kubevirt/kubevirt/pull/8359#issuecomment-1242916295), but would create a manual backport soon.

**Comment by Barakmor1** [comment]
@ksimon1 
I think that we are good now.
Can you have a look?

**Comment by 0xFelix** [comment]
Looks good to me, can you please add an entry to `README.md`?

**Comment by Barakmor1** [comment]
> Looks good to me, can you please add an entry to `README.md`?

Thanks for the note i totally missed that file :)

**Review by 0xFelix — APPROVED** [review]

**Comment by akrejcir** [comment]
The tests are currently broken on the latest CDI release v1.55.0.

**Comment by Barakmor1** [comment]
> The tests are currently broken with the latest CDI release v1.55.0.

thanks for letting me know :)

**Comment by fossedihelm** [comment]
/hold

Need to wait that the fix for failing lanes will land (https://github.com/kubevirt/common-templates/pull/481)

**Pull request merged**
