### PR TITLE
Improve openSUSE template

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

- Correct spelling of openSUSE
- Automatically load active openSUSE versions

**Release note**:

```release-note
Include support for latest and active openSUSE versions
```

### CODE REVIEW

**Comment by dominikholler** [comment]
@0xFelix is this PR required to depend on https://github.com/kubevirt/common-templates/pull/406 , or can it be also merged before?

**Comment by 0xFelix** [comment]
@dominikholler I could extract the import urls and then it would be independent.

**Comment by 0xFelix** [comment]
@dominikholler It is independent now.

**Review by dominikholler — APPROVED** [review]
/lgtm

**Pull request merged**
