### PR TITLE
Add initial go test suite

### PR DESCRIPTION
**Pull request by vatsalparekh**
**What this PR does / why we need it**:
Add initial go test suite to run with https://github.com/openshift/release/pull/21019 

**Special notes for your reviewer**:
This is just the empty test suite right now so that #366 can directly go with adding its test on top of this and check it against a functest lane

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by akrejcir — CHANGES_REQUESTED** [review]
Can you please add more information to the commit message? It should include the reason WHY this change is done.

**Comment by akrejcir** [comment]
There is a typo in the commit message title.
Otherwise looks good.

**Comment by akrejcir** [comment]
Looks good. Let's see if the CI passes.
We will need to change the offensive lang script to ignore vendor folder.

**Comment by ksimon1** [comment]
can you please exclude the vendor folder from validate-no-offensive-lang script?

**Pull request merged**
