### PR TITLE
Remove useless osinfo-db-override for windows 11

### PR DESCRIPTION
**Pull request by fossedihelm**
**What this PR does / why we need it**:
Windows 11 os info has been included in the osinfo-db repository. https://gitlab.com/libosinfo/osinfo-db/-/merge_requests/362

It is not necessary anymore to use our custom data
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
Thanks!

/approve
/lgtm

**Comment by fossedihelm** [comment]
> /hold Merge after #518

@0xFelix FYI, previous osinfo-db already contains win11 information, so we don't need to wait for the 518

**Pull request merged**
