### PR TITLE
Update osinfo-db to v20230719-3-g6c814a39

### PR DESCRIPTION
**Pull request by ksimon1**
Update osinfo-db to v20230719-3-g6c814a39
**Release note**:
```release-note
Update osinfo-db to v20230719-3-g6c814a39
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]
/approve
/lgtm

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by ksimon1** [comment]
this PR is blocked by https://github.com/kubevirt/containerized-data-importer/issues/2836

**Pull request closed without merging**
