### PR TITLE
Update osinfo-db to v20221130-51-g3104778a

### PR DESCRIPTION
**Pull request by ksimon1**
Update osinfo-db to v20221130-51-g3104778a
**Release note**:
```release-note
Update osinfo-db to v20221130-51-g3104778a
```

### CODE REVIEW

**Review by 0xFelix — APPROVED** [review]

**Comment by fossedihelm** [comment]
IMO this can be closed in favor of https://github.com/kubevirt/common-templates/pull/518

**Comment by 0xFelix** [comment]
Indeed, closed in favor of #518

**Pull request closed without merging**
