### PR TITLE
Adopt UEFI in Windows 2k12, 2k16 and 2k19

### PR DESCRIPTION
**Pull request by fossedihelm**
Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.

**What this PR does / why we need it**:
Adopt UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Adopted UEFI in Windows 2k12, 2k16 and 2k19 by enabling EFI and Secureboot in the respective templates.
```

### CODE REVIEW

**Review by 0xFelix — COMMENTED** [review]
/approve

Thanks!

Please note: For e2e tests to pass the used images likely need to be updated to support EFI boot.

**Comment by ksimon1** [comment]
/lgtm
/approve
As Felix said, We will need new images, which supports EFI. If you can send me links to them, I can push them to correct places.

**Comment by fossedihelm** [comment]
> /lgtm /approve As Felix said, We will need new images, which supports EFI. If you can send me links to them, I can push them to correct places.

:+1: working on it! Thanks

**Pull request merged**
